### ISSUE TITLE
Fiat Calculation isn't fully accurate

### ISSUE THREAD

**Issue by DatDraggy** [jouir/mining-dashboards#6]
https://img.kieran.de/r2zDpPo.png
This should be around 407€

**Comment by jouir** [comment]
Hello,

Thanks for the report. A fix has been Implemented in 2d5007d.

Have a nice day,

**Comment by DatDraggy** [comment]
I think I'm noticing a similar issue. That's 26€
![Screenshot](https://img.kieran.de/lLutTOD.png)

**Comment by jouir** [comment]
I tried to reproduce the issue with my own graph this morning, same time zone, same fiat currency, but numbers look good to me:

```
$ date; rate=$(curl -s -XGET 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=eur' | jq -r '.ethereum.eur'); echo $rate; echo "$rate*0.031942" | bc
Mon 10 May 2021 08:45:21 AM CEST
3383.45
108.074159
```

![Screenshot from 2021-05-10 08-44-24](https://user-images.githubusercontent.com/24910974/117617205-7dcb6c80-b16c-11eb-82d0-3e86f0414078.png)

Where do you find your conversion rate?

**Comment by DatDraggy** [comment]
I just found the issue. For some reason this was in my URL
![ScreenshotMerp](https://img.kieran.de/9GI6nBY.png)
